const API_BASE = String(window.COC_API_BASE || "").replace(/\/$/, "");
const state = { token: "", tag: "", player: null };
const $ = id => document.getElementById(id);
const esc = v => String(v ?? "").replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;").replaceAll("'","&#039;");
const fmt = v => v == null ? "—" : Number(v).toLocaleString();
function setError(msg){const e=$("connectError");e.textContent=msg||"";e.classList.toggle("hidden",!msg)}
function setConnected(on){const e=$("connectionPill");e.classList.toggle("muted",!on);e.innerHTML=on?'<span class="status-dot"></span> Connected':'<span class="status-dot"></span> Disconnected'}
function pct(items){if(!Array.isArray(items)||!items.length)return null;const v=items.filter(x=>Number.isFinite(Number(x.progress)));return v.length?v.reduce((s,x)=>s+Number(x.progress),0)/v.length:null}
function row(x){const l=x.level??"—",m=x.maxLevel??x.maxLevelForTownHall??"—",p=Number.isFinite(Number(x.progress))?Math.max(0,Math.min(100,Number(x.progress))):null;return `<div class="entity-row"><div class="entity-head"><strong>${esc(x.name)}</strong><span>${esc(l)}${m!=="—"?` / ${esc(m)}`:""}</span></div>${p!==null?`<div class="progress-track"><div class="progress-fill" style="width:${p}%"></div></div>`:""}</div>`}
function render(p){state.player=p;$("connectView").classList.add("hidden");$("dashboardView").classList.remove("hidden");setConnected(true);$("playerName").textContent=p.name||"Unknown Player";$("playerMeta").textContent=`${p.tag||state.tag||"#PLAYER"} · ${p.clan?.name||"No Clan"}`;$("townHallValue").textContent=p.townHallLevel??"—";$("xpValue").textContent=fmt(p.expLevel);$("trophiesValue").textContent=fmt(p.trophies);$("bestTrophiesValue").textContent=fmt(p.bestTrophies);$("leagueBadge").textContent=p.league?.name||"Unranked";$("attackWins").textContent=fmt(p.attackWins);$("defenseWins").textContent=fmt(p.defenseWins);$("donations").textContent=fmt(p.donations);$("clanValue").textContent=p.clan?.name||"—";
const areas=[["Heroes",pct(p.heroes)],["Troops",pct(p.troops)],["Spells",pct(p.spells)],["Hero Equipment",pct(p.heroEquipment)],["Pets",pct(p.pets)]].filter(([,v])=>v!==null);$("progressList").innerHTML=areas.length?areas.map(([n,v])=>`<div class="progress-item"><div class="progress-head"><span>${esc(n)}</span><strong>${Math.round(v)}%</strong></div><div class="progress-track"><div class="progress-fill" style="width:${Math.max(0,Math.min(100,v))}%"></div></div></div>`).join(""): '<div class="muted-text">No progression arrays are available in the API payload.</div>';const all=areas.map(([,v])=>v),overall=all.length?Math.round(all.reduce((a,b)=>a+b,0)/all.length):0;$("overallScore").textContent=`${overall}%`;$("overallScoreRing").style.background=`conic-gradient(var(--accent) ${overall}%, var(--track) ${overall}%)`;
[["heroesList","heroCount",p.heroes],["troopsList","troopCount",p.troops],["spellsList","spellCount",p.spells],["equipmentList","equipmentCount",p.heroEquipment]].forEach(([lid,cid,list])=>{const a=Array.isArray(list)?list:[];$(cid).textContent=`${a.length} tracked`;$(lid).innerHTML=a.length?a.map(row).join(""):'<div class="muted-text">No data available.</div>'})}
async function fetchPlayer(tag,token){if(!API_BASE)throw new Error("Live API backend is not configured yet. Deploy the backend and set API_BASE in config.js.");const cleanTag=tag.replace(/^#/,'');const response=await fetch(`${API_BASE}/player/${encodeURIComponent(cleanTag)}`,{headers:{Authorization:`Bearer ${token}`,Accept:"application/json"}});let body=null;try{body=await response.json()}catch(_){}if(!response.ok){const m=body?.message||body?.reason||body?.detail;throw new Error(m?`${m} (HTTP ${response.status})`:`API request failed (HTTP ${response.status}).`)}return body}
async function connect(){setError("");const tag=$("playerTag").value.trim().toUpperCase(),token=$("apiToken").value.trim();if(!tag)return setError("Enter a Player Tag, for example #9ABC1234.");if(!token)return setError("Enter your Clash of Clans API token.");state.tag=tag;state.token=token;$("connectButton").disabled=true;$("connectButton").textContent="Loading…";try{render(await fetchPlayer(tag,token))}catch(error){setConnected(false);setError(error.message||"Unable to load the account.")}finally{$("connectButton").disabled=false;$("connectButton").textContent="Connect & Load Dashboard"}}
function disconnect(){state.token="";state.tag="";state.player=null;$("apiToken").value="";$("dashboardView").classList.add("hidden");$("connectView").classList.remove("hidden");setConnected(false);setError("")}
function toggleTheme(){const light=document.documentElement.classList.toggle("light");localStorage.setItem("coc-theme",light?"light":"dark");$("themeToggle").textContent=light?"☀":"☾"}
function init(){if(localStorage.getItem("coc-theme")==="light"){document.documentElement.classList.add("light");$("themeToggle").textContent="☀"}$("connectButton").addEventListener("click",connect);$("disconnectButton").addEventListener("click",disconnect);$("themeToggle").addEventListener("click",toggleTheme);$("refreshButton").addEventListener("click",()=>{if(state.tag&&state.token)connect()});["apiToken","playerTag"].forEach(id=>$(id).addEventListener("keydown",e=>{if(e.key==="Enter")connect()}))}
document.addEventListener("DOMContentLoaded",init);
